MyJobDating\Bundle\UserBundle\Entity\Candidate:
    type: entity
    table: candidate
    id:
        id:
            type: integer
            id: true
            strategy:
                generator: AUTO
    oneToOne:
        user:
            targetEntity: MyJobDating\Bundle\UserBundle\Entity\User
            inversedBy: candidate
            joinColumn:
                name: user_id
                referencedColumnName: id
