MyJobDating\Bundle\UserBundle\Entity\Candidate:
    type: entity
    table: candidate
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO

    fields:
        description:
            type: string
            length: 255
            nullable: true

    manyToMany:
        skills:
            targetEntity: MyJobDating\Bundle\SkillBundle\Entity\Skill
            joinTable:
                name: user_skill
                joinColumns:
                    user_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id
