MyJobDating\Bundle\UserBundle\Entity\Company:
    type: entity
    table: company
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 64
        createdAt:
            type: datetime
            column: created_at
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
