MyJobDating\Bundle\UserBundle\Entity\Recruiter:
    type: entity
    table: recruiter
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
