MyJobDating\Bundle\OfferBundle\Entity\Offer:
    type: entity
    table: offer
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        title:
            type: string
            length: 50

        description:
            type: string
            length: 1024


        createdAt:
            type: datetime
            column: created_at
            nullable: true
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update

        enabled:
            type: boolean
            nullable: false
            options:
                default: true

        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true

    oneToOne:
        recruiter:
            targetEntity: MyJobDating\Bundle\UserBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id

    manyToMany:
        skills:
            targetEntity: MyJobDating\Bundle\SkillBundle\Entity\Skill
            joinTable:
                name: offer_skill
                joinColumns:
                    offer_id:
                        referencedColumnName: id

                inverseJoinColumns:
                    skill_id:
                        referencedColumnName: id

    properties:
        name:
            - NotBlank: ~