myjobdating_user_authentication_login:
    path: /login
    defaults:
        _controller: MyJobDatingUserBundle:Authentication:login

myjobdating_user_authentication_register:
    path: /register
    defaults:
        _controller: MyJobDatingUserBundle:Authentication:register

myjobdating_user_authentication_logout:
    path: /logout
