offer:
    resource: "@MyJobDatingOfferBundle/Resources/config/routing.yml"
    prefix:   /

skill:
    resource: "@MyJobDatingSkillBundle/Resources/config/routing.yml"
    prefix:   /

myjobdating_core:
    resource: "@MyJobDatingCoreBundle/Resources/config/routing.yml"
