myjobdating_admin:
    resource: "@MyJobDatingAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

offer:
    resource: "@MyJobDatingOfferBundle/Resources/config/routing.yml"
    prefix:   /

myjobdating_core:
    resource: "@MyJobDatingCoreBundle/Resources/config/routing.yml"

myjobdating_user:
    resource: "@MyJobDatingUserBundle/Resources/config/routing.yml"

myjobdating_skill:
    resource: "@MyJobDatingSkillBundle/Resources/config/routing.yml"
    prefix:   /
