security:

    encoders:
        MyJobDating\Bundle\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_CANDIDATE: ~
        ROLE_RECRUITER: ~
        ROLE_ADMIN: ['ROLE_CANDIDATE', 'ROlE RECRUITER']

    providers:
        myjobdating_basic_users_provider:
            entity:
                class: MyJobDatingUserBundle:User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            http_basic: ~
            provider: myjobdating_basic_users_provider
            logout_on_user_change: true
            anonymous: ~
            form_login:
                csrf_token_generator: security.csrf.token_manager
                default_target_path: myjobdating_core_homepage
                login_path: myjobdating_user_authentication_login
                check_path: myjobdating_user_authentication_login
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /
                always_remember_me: false
            logout:
                success_handler: myjobdating.handler.logout_success_handler
                path: /logout
                target: /

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, roles: ROLE_ADMIN }
