skill_homepage:
    path:     /admin/skills
    defaults: { _controller: MyJobDatingSkillBundle:Skill:index }

myjobdating_level_index:
    path: /admin/level
    defaults:
        _controller: MyJobDatingSkillBundle:Level:index
