myjobdating_admin_homepage:
    path:     /
    defaults: { _controller: AdminBundle:Home:index }

myjobdating_admin_skills:
    resource: "@MyJobDatingAdminBundle/Resources/config/routing/skills.yml"
    prefix: /skills
