MyJobDating\Bundle\SkillBundle\Entity\Skill:
  type: entity
  table: skill
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  fields:
    name:
      type: string
      length: 64
  uniqueConstraints:
    uniqueName:
      columns: ['name']