MyJobDating\Bundle\SkillBundle\Entity\Skill:
    type: entity
    table: skill
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    fields:
        name:
            type: string
            length: 30
            nullable: false
            unique: true

        createdAt:
            type: datetime
            column: created_at
            nullable: true
            gedmo:
                timestampable:
                    on: create

        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update

    properties:
        name:
            - NotBlank: ~