MyJobDating\Bundle\AdminBundle\Entity\Admin:
    type: entity
    table: admin
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        email:
            type: string
            length: 64
            unique: true
        password:
            type: string
            length: 64
        enabled:
            type: boolean
            nullable: false
            options:
                default: false
        createdAt:
            type: datetime
            column: created_at
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            column: updated_at
            nullable: true
            gedmo:
                timestampable:
                    on: update
        deletedAt:
            type: datetime
            column: deleted_at
            nullable: true
    properties:
        email:
            - NotBlank: ~
            - Email: ~
        plainPassword:
            - NotBlank: ~
            - Length:
                max: 4096
    lifecycleCallbacks: {  }
