offer_homepage:
    path: /user/offers
    defaults: { _controller: MyJobDatingOfferBundle:Offer:index }

offer_add:
    path: /user/offers/add
    defaults: { _controller: MyJobDatingOfferBundle:Offer:add }
